### ISSUE TITLE
Syncing CAPS with Personnel Scheduling System

### ISSUE THREAD

**Issue by brendanbailey** [CityOfLosAngeles/data-workflows-101#10]
I want to sync CAPS and the Personnel Scheduling System using something more robust than cron

**Comment by hunterowens** [comment]
Hey @brendanbailey do you want CAPS or PSS to be the system of record-  ie, where should the data entry first occur

**Comment by brendanbailey** [comment]
PSS

**Comment by hunterowens** [comment]
alright, I've got this. Should have a pull request available in a little bit

**Comment by brendanbailey** [comment]
Looks good you can merge
